---
- name: Get libcontainers yum repo
  ansible.builtin.get_url:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ OS }}/devel:kubic:libcontainers:stable.repo
    dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
  vars:
    OS: CentOS_7

- name: Get CRIO repo
  ansible.builtin.get_url:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ VERSION }}/{{ OS }}/devel:kubic:libcontainers:stable:cri-o:{{ VERSION }}.repo
    dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:{{ VERSION }}.repo
  vars:
    OS: CentOS_7
    VERSION: 1.24

- name: Install CRIO container engine
  ansible.builtin.yum:
    name: cri-o
    state: latest
    update_cache: yes

- name: Enable and start CRIO
  ansible.builtin.systemd:
    name: crio
    daemon_reload: yes
    enabled: yes
    state: started
