---
- name: Pull control-plane required images
  ansible.builtin.shell: |
    kubeadm config images pull
  args:
    executable: /bin/bash

- name: Initialize kubernetes control-plane
  ansible.builtin.shell: |
    kubeadm init \
      --control-plane-endpoint={{ ansible_hostname }}:{{ k8s_apiserver_port }} \
      --pod-network-cidr={{ pod_nw_cidr }} \
      --service-cidr={{ svc_cidr }} \
      --cri-socket=unix:///var/run/crio/crio.sock \
      --ignore-preflight-errors=NumCPU,Mem
  args:
    executable: /bin/bash
  register: output
- debug:
    msg: "{{ output.stdout_lines }}"

- name: Pause for 3 minutes
  ansible.builtin.pause:
    minutes: 3

# - name: Create directory for calico manifest
#   ansible.builtin.file:
#     path: /etc/calico-cni
#     state: directory
#     recurse: yes
# - name: Download Calico CNI manifest file
#   ansible.builtin.get_url:
#     url: https://docs.projectcalico.org/manifests/calico.yaml
#     dest: /etc/calico-cni/calico.yaml
# - name: Create backup manifest file
#   ansible.builtin.copy:
#     remote_src: yes
#     src: /etc/calico-cni/calico.yaml
#     dest: /etc/calico-cni/calico.backup.yaml
# - name: Update Calico manifest
#   ansible.builtin.shell: |
#     cidr=$(grep "^[[:space:]]*\#" /etc/calico-cni/calico.yaml | grep -oP "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\/[0-9]*")
#     sed -i "s#${cidr}#{{ pod_nw_cidr }}#" /etc/calico-cni/calico.yaml
#   args:
#     executable: /bin/bash
# - name: Install Calico on k8s cluster
#   ansible.builtin.shell: |
#     kubectl apply -f /etc/calico-cni/calico.yaml
#   environment:
#     KUBECONFIG: /etc/kubernetes/admin.conf
#   args:
#     executable: /bin/bash

- name: Create directory for canal manifest
  ansible.builtin.file:
    path: /etc/canal-cni
    state: directory
    recurse: yes
- name: Download Canal CNI manifest file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/canal.yaml
    dest: /etc/canal-cni/canal.yaml
- name: Create backup manifest file
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/canal-cni/canal.yaml
    dest: /etc/canal-cni/canal.backup.yaml
- name: Update Canal manifest
  ansible.builtin.shell: |
    cidr=$(grep "\"Network\"\:" /etc/canal-cni/canal.yaml | grep -oP "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\/[0-9]*")
    sed -i "s#${cidr}#{{ pod_nw_cidr }}#" /etc/canal-cni/canal.yaml
  args:
    executable: /bin/bash
- name: Install Canal on k8s cluster
  ansible.builtin.shell: |
    kubectl apply -f /etc/canal-cni/canal.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  args:
    executable: /bin/bash

- name: Pause for 3 minutes
  ansible.builtin.pause:
    minutes: 3

- name: Save join-command
  ansible.builtin.shell: |
    kubeadm token create --print-join-command | sed "s/localhost/$(hostname)/" > /tmp/join-cmd.txt
  args:
    executable: /bin/bash

- name: Fetch join-command file back to ansible server
  ansible.builtin.fetch:
    src: /tmp/join-cmd.txt
    dest: /tmp/
    flat: yes















# - name: Create directory for calicoctl
#   ansible.builtin.file:
#     path: /opt/calico
#     state: directory
#     recurse: yes
# - name: Download Calico CLI tool
#   ansible.builtin.get_url:
#     url: https://github.com/projectcalico/calico/releases/download/v3.24.1/calicoctl-linux-amd64 -o calicoctl
#     dest: /opt/calico/calicoctl
# - name: Install calicoctl
#   ansible.builtin.shell: |
#     install -o root -g root -m 0775 /opt/calico/calicoctl usr/bin/calicoctl
#   args:
#     executable: /bin/bash


